services:
  - type: web
    name: goodwe-api
    runtime: python
    env: production
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    disk: 0